import PDFDocument from "pdfkit";
import { prisma } from "../config/prisma";
import { requireOwnedActivityData } from "./steelActivityData.service";
import { computeCbamFinancialImpact } from "./cbamFinancialImpact.service";
import { buildCbamCommunicationPackage } from "./cbamReport/build";

const TEAL = "#00A886";
const NAVY = "#0F1923";
const MUTED = "#5B6B7A";
const BORDER = "#D8DEE4";

export type ReportType = "CBAM" | "CCTS";

export const getReportContext = async (userId: string, facilityId: string, activityDataId: string) => {
  await requireOwnedActivityData(userId, facilityId, activityDataId);

  const activityData = await prisma.steelActivityData.findUniqueOrThrow({
    where: { id: activityDataId },
    include: {
      facility: { include: { company: { include: { owner: true } } } },
      fuelEntries: true,
      processMaterialEntries: true,
      precursorEntries: true,
      calculationResult: true,
      verificationRequest: { include: { verifier: true } },
    },
  });

  if (!activityData.calculationResult) {
    throw new Error("Activity data has not been calculated yet");
  }

  return activityData;
};

export type ReportContext = Awaited<ReturnType<typeof getReportContext>>;

const fmt = (n: number, digits = 3) =>
  n.toLocaleString("en-IN", { maximumFractionDigits: digits, minimumFractionDigits: digits });
const fmtDate = (d: Date) => d.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });

class Cursor {
  y: number;
  constructor(
    private doc: PDFKit.PDFDocument,
    y: number,
  ) {
    this.y = y;
  }

  ensureSpace(needed: number) {
    if (this.y + needed > this.doc.page.height - 60) {
      this.doc.addPage();
      this.y = 50;
    }
  }

  heading(text: string) {
    this.ensureSpace(30);
    this.doc.fillColor(NAVY).font("Helvetica-Bold").fontSize(13).text(text, 50, this.y);
    this.y += 20;
    this.doc.moveTo(50, this.y).lineTo(545, this.y).strokeColor(BORDER).lineWidth(1).stroke();
    this.y += 12;
  }

  paragraph(text: string, opts: { color?: string; size?: number; bold?: boolean } = {}) {
    this.ensureSpace(20);
    this.doc
      .fillColor(opts.color ?? "#1A2530")
      .font(opts.bold ? "Helvetica-Bold" : "Helvetica")
      .fontSize(opts.size ?? 10)
      .text(text, 50, this.y, { width: 495 });
    this.y = this.doc.y + 8;
  }

  keyValueRow(label: string, value: string) {
    this.ensureSpace(16);
    this.doc.fillColor(MUTED).font("Helvetica").fontSize(9.5).text(label, 50, this.y, { width: 180 });
    this.doc.fillColor("#1A2530").font("Helvetica-Bold").fontSize(9.5).text(value, 230, this.y, { width: 315 });
    this.y += 16;
  }

  table(headers: string[], rows: (string | number)[][], colWidths: number[]) {
    this.ensureSpace(20 + rows.length * 14);
    let x = 50;
    this.doc.font("Helvetica-Bold").fontSize(8.5).fillColor(NAVY);
    headers.forEach((h, i) => {
      this.doc.text(h, x, this.y, { width: colWidths[i] });
      x += colWidths[i];
    });
    this.y += 14;
    this.doc.moveTo(50, this.y - 3).lineTo(545, this.y - 3).strokeColor(BORDER).stroke();

    this.doc.font("Helvetica").fontSize(8.5).fillColor("#1A2530");
    rows.forEach((row) => {
      this.ensureSpace(14);
      x = 50;
      row.forEach((cell, i) => {
        this.doc.text(String(cell), x, this.y, { width: colWidths[i] });
        x += colWidths[i];
      });
      this.y += 14;
    });
    this.y += 8;
  }

  scoreBox(label: string, value: string, sublabel: string) {
    this.ensureSpace(70);
    const boxY = this.y;
    this.doc.roundedRect(50, boxY, 495, 60, 6).fillColor("#EFFBF7").fill();
    this.doc.fillColor(TEAL).font("Helvetica-Bold").fontSize(10).text(label, 66, boxY + 10);
    this.doc.fillColor(NAVY).font("Helvetica-Bold").fontSize(22).text(value, 66, boxY + 24);
    this.doc.fillColor(MUTED).font("Helvetica").fontSize(8.5).text(sublabel, 66, boxY + 48);
    this.y = boxY + 72;
  }
}

const drawHeader = (doc: PDFKit.PDFDocument, title: string, subtitle: string) => {
  doc.rect(0, 0, doc.page.width, 90).fillColor(NAVY).fill();
  doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(16).text("Intellocarbon", 50, 28);
  doc.fillColor(TEAL).font("Helvetica-Bold").fontSize(11).text(title, 50, 50);
  doc.fillColor("#B5C0CC").font("Helvetica").fontSize(9).text(subtitle, 50, 66);
  doc.fillColor("#B5C0CC").font("Helvetica").fontSize(8).text(`Generated ${fmtDate(new Date())}`, 400, 50, {
    width: 145,
    align: "right",
  });
};

const drawFooter = (doc: PDFKit.PDFDocument) => {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc
      .fillColor(MUTED)
      .font("Helvetica")
      .fontSize(7.5)
      .text(
        "Indicative Tier-1 calculation using default emission factors. Not a substitute for a certified regulatory submission. Generated by Intellocarbon.",
        50,
        doc.page.height - 32,
        { width: 495, align: "center", lineBreak: false },
      );
  }
};

const writeCompanyAndFacility = (c: Cursor, ctx: ReportContext) => {
  const { facility } = ctx;
  const { company } = facility;

  c.heading("Reporting entity");
  c.keyValueRow("Company", company.name);
  if (company.registrationNumber) c.keyValueRow("Registration number", company.registrationNumber);
  c.keyValueRow("Sector", company.sector);
  c.keyValueRow(
    "Location",
    [company.city, company.state, company.country].filter(Boolean).join(", "),
  );
  c.y += 6;

  c.heading("Facility");
  c.keyValueRow("Facility name", facility.name);
  c.keyValueRow("Facility type", facility.facilityType.replace(/_/g, " "));
  c.keyValueRow("Production route", facility.productionRoute.replace(/_/g, " "));
  if (facility.installedCapacityTpa) {
    c.keyValueRow("Installed capacity", `${facility.installedCapacityTpa.toLocaleString("en-IN")} tonnes/year`);
  }
  c.y += 6;

  c.heading("Reporting period");
  c.keyValueRow("Period", `${fmtDate(ctx.periodStart)} – ${fmtDate(ctx.periodEnd)}`);
  c.keyValueRow("Product category", ctx.productCategory);
  c.keyValueRow("Production quantity", `${ctx.productionQuantityT.toLocaleString("en-IN")} tonnes`);
  c.y += 6;
};

const writeVerificationBlock = (c: Cursor, ctx: ReportContext) => {
  c.heading("Independent verification");
  const vr = ctx.verificationRequest;
  if (!vr) {
    c.paragraph("This report has not been submitted for independent verification.", { color: MUTED });
    return;
  }
  if (vr.status === "APPROVED") {
    c.paragraph(
      `Verified and approved by ${vr.verifier?.name ?? "an independent verifier"}${
        vr.verifierOrg ? ` (${vr.verifierOrg})` : ""
      } on ${vr.decidedAt ? fmtDate(vr.decidedAt) : "—"}.`,
      { color: TEAL, bold: true },
    );
    if (vr.statement) c.paragraph(vr.statement, { color: "#1A2530" });
  } else if (vr.status === "REJECTED") {
    c.paragraph(
      `This submission was reviewed and rejected by ${vr.verifier?.name ?? "an independent verifier"} on ${
        vr.decidedAt ? fmtDate(vr.decidedAt) : "—"
      }.`,
      { color: "#B33A3A", bold: true },
    );
    if (vr.comments) c.paragraph(vr.comments, { color: "#1A2530" });
  } else {
    c.paragraph(`Verification status: ${vr.status.replace(/_/g, " ")}.`, { color: MUTED });
  }
  c.y += 6;
};

export const buildCbamReportPdf = (doc: PDFKit.PDFDocument, ctx: ReportContext) => {
  const financials = computeCbamFinancialImpact(ctx);
  buildCbamCommunicationPackage(doc, ctx, financials);
};

export const buildCctsReportPdf = (doc: PDFKit.PDFDocument, ctx: ReportContext) => {
  const result = ctx.calculationResult!;
  drawHeader(doc, "CCTS GHG Intensity Report", "India Carbon Credit Trading Scheme");

  const c = new Cursor(doc, 110);
  writeCompanyAndFacility(c, ctx);

  c.heading("Methodology");
  c.paragraph(
    "GHG intensity is calculated as total direct and indirect emissions (Scope 1 + Scope 2), plus embedded emissions from precursor materials, divided by production quantity. Non-CO2 gases are converted to CO2e using IPCC AR4 100-year Global Warming Potentials, consistent with India's PAT scheme / GHG Programme convention (CH4 = 25, N2O = 298).",
  );

  c.scoreBox(
    "GHG INTENSITY",
    `${fmt(result.ghgIntensityCcts)} tCO2e / t product`,
    `Total emissions for period: ${result.totalEmissionsCctsAr4.toLocaleString("en-IN", { maximumFractionDigits: 1 })} tCO2e`,
  );

  c.heading("Emissions breakdown (AR4 GWP)");
  c.table(
    ["Category", "tCO2e"],
    [
      ["Direct combustion (fuels)", fmt(result.directCombustionCo2eAr4, 2)],
      ["Process emissions", fmt(result.directProcessCo2e, 2)],
      ["Precursor materials (embedded)", fmt(result.directPrecursorCo2e, 2)],
      ["Electricity (indirect)", fmt(result.indirectElectricityCo2e, 2)],
      ["Steam (indirect)", fmt(result.indirectSteamCo2e, 2)],
    ],
    [350, 145],
  );

  if (ctx.processMaterialEntries.length > 0) {
    c.heading("Process material detail");
    c.table(
      ["Material", "Quantity (t)", ""],
      ctx.processMaterialEntries.map((m) => [m.materialType.replace(/_/g, " "), m.quantityTonnes.toLocaleString("en-IN"), ""]),
      [250, 150, 95],
    );
  }

  writeVerificationBlock(c, ctx);
  drawFooter(doc);
};

export const generateReportPdf = (ctx: ReportContext, type: ReportType): PDFKit.PDFDocument => {
  const doc = new PDFDocument({
    size: "A4",
    margins: { top: 50, left: 50, right: 50, bottom: 20 },
    bufferPages: true,
  });
  if (type === "CBAM") {
    buildCbamReportPdf(doc, ctx);
  } else {
    buildCctsReportPdf(doc, ctx);
  }
  return doc;
};
