import type { Metadata } from "next";
import { MarketingHeader } from "@/components/intellocalc/marketing-header";
import { ToolFooter } from "@/components/intellocalc/tool-footer";

export const metadata: Metadata = {
  title: "Terms of Service — Intellocarbon",
  description:
    "Terms of Service governing access to and use of the Intellocarbon platform, operated by Intellocarbon Solutions Private Limited.",
};

const SECTIONS = [
  {
    heading: "1. Nature of the Service",
    paragraphs: [
      'Intellocarbon provides a software-as-a-service platform that enables users to enter facility-level activity data (fuel, electricity, process material, and precursor data) and generates calculation outputs and reports relevant to the EU Carbon Border Adjustment Mechanism (CBAM), India’s Carbon Credit Trading Scheme (CCTS), BRSR Core disclosures, and related compliance frameworks, based on regulatory methodologies and emission factors maintained on the Platform.',
      "1.1 The Platform is a calculation, record-keeping, and reporting tool. It is not a substitute for professional legal, tax, accounting, or regulatory advice, and does not itself constitute regulatory submission, filing, or certification.",
      "1.2 Outputs generated by the Platform (including CBAM Communication Packages, CCTS GHG Intensity Reports, and BRSR Core Reports) are based entirely on data supplied by the Customer. Intellocarbon does not independently verify, audit, or validate the accuracy or completeness of Customer-submitted data.",
      "1.3 Where the Platform references third-party verifiers, verification through the Platform's verifier portal does not constitute a guarantee of regulatory acceptance by any government body, buyer, or authority.",
    ],
  },
  {
    heading: "2. Accounts and Access",
    paragraphs: [
      "2.1 Customer must provide accurate registration information and is responsible for maintaining the confidentiality of login credentials for all users under its account.",
      "2.2 Customer is responsible for all activity that occurs under its account, including activity by its Company Admin, Data Entry Operators, and any other users it authorises.",
      "2.3 Intellocarbon reserves the right to suspend or terminate access for breach of these Terms, non-payment, or misuse of the Platform, including attempts to circumvent usage limits or security controls.",
    ],
  },
  {
    heading: "3. Subscription, Fees and Billing",
    paragraphs: [
      "3.1 Access to the Platform is provided on a subscription basis, billed monthly per facility, at the rates displayed on the Billing page at the time of subscription. Intellocarbon may revise pricing prospectively with notice; existing billing cycles will not be changed retroactively without consent.",
      "3.2 Fees are exclusive of applicable taxes (including GST), which will be added at checkout where applicable.",
      "3.3 Subscriptions renew automatically each billing cycle unless cancelled by the Customer prior to renewal. Cancelled subscriptions remain active until the end of the current paid period.",
      "3.4 Onboarding fees, where applicable, are one-time and non-refundable once onboarding services have commenced.",
      "3.5 Non-payment may result in suspension of access, including restriction of report generation and data export, until dues are cleared.",
    ],
  },
  {
    heading: "4. Customer Data and Responsibilities",
    paragraphs: [
      'Customer retains ownership of all data it inputs into the Platform ("Customer Data"). Customer is solely responsible for the accuracy, completeness, and lawfulness of Customer Data.',
      "4.2 Customer represents that it has the right to submit any data entered into the Platform, including data relating to suppliers, precursors, or third parties.",
      "4.3 Emission factors, default values, and regulatory reference data maintained on the Platform are sourced from and cited to the applicable regulation, methodology document, or government publication in force at the time of use. Where Customer overrides a default value with facility-specific data, Customer is responsible for the accuracy of that override.",
    ],
  },
  {
    heading: "5. Intellectual Property",
    paragraphs: [
      "5.1 The Platform, including its software, calculation methodology implementation, design, and all associated intellectual property, is owned by Intellocarbon. These Terms do not transfer any ownership rights to Customer.",
      "5.2 Customer is granted a limited, non-exclusive, non-transferable right to access and use the Platform for its internal business purposes during the subscription term.",
      "5.3 Reports generated for Customer's own facilities may be used, shared, and submitted by Customer for its own regulatory and business purposes.",
    ],
  },
  {
    heading: "6. Verification Portal",
    paragraphs: [
      "6.1 Where a third-party verifier is engaged through the Platform's verification workflow, the verifier operates independently and is solely responsible for the content, accuracy, and conclusions of any verification statement issued.",
      "6.2 Intellocarbon does not act as an accredited verification or certification body and makes no representation regarding the qualifications of any verifier using the Platform, beyond information the verifier itself provides.",
    ],
  },
  {
    heading: "7. Disclaimers and Limitation of Liability",
    paragraphs: [
      "7.1 The Platform provides calculation and reporting tools based on data supplied by Customer and applicable regulations at the time of use. Final compliance responsibility rests with the Customer and its appointed verifier or auditor.",
      "7.2 Intellocarbon is not liable for penalties, fines, rejected filings, or other adverse regulatory outcomes arising from inaccurate Customer-submitted data, or from regulatory changes not yet reflected on the Platform at the time a report was generated.",
      "7.3 To the maximum extent permitted by applicable law, Intellocarbon's aggregate liability arising out of or relating to these Terms or the Platform shall not exceed the fees paid by Customer in the twelve (12) months preceding the claim.",
      '7.4 The Platform is provided "as is" and "as available." Intellocarbon does not warrant uninterrupted or error-free operation of the Platform.',
    ],
  },
  {
    heading: "8. Confidentiality",
    paragraphs: [
      "Each party agrees to keep confidential any non-public business, technical, or financial information disclosed by the other party in connection with these Terms, and to use such information solely for purposes of the relationship between the parties.",
    ],
  },
  {
    heading: "9. Term and Termination",
    paragraphs: [
      "9.1 These Terms remain in effect for as long as Customer maintains an active subscription or account on the Platform.",
      "9.2 Upon termination, Customer's access to the Platform will cease. Intellocarbon may retain Customer Data for the period required under applicable regulatory retention requirements (including the 7-year retention period applicable to CBAM-related records), after which it may be deleted.",
    ],
  },
  {
    heading: "10. Governing Law and Jurisdiction",
    paragraphs: [
      "These Terms shall be governed by the laws of India. Courts at Ambikapur, Chhattisgarh shall have exclusive jurisdiction over any disputes arising out of or in connection with these Terms.",
    ],
  },
  {
    heading: "11. Changes to These Terms",
    paragraphs: [
      "Intellocarbon may update these Terms from time to time. Material changes will be notified to Customer via email or in-platform notice. Continued use of the Platform after such notice constitutes acceptance of the revised Terms.",
    ],
  },
  {
    heading: "12. Contact",
    paragraphs: ["For questions regarding these Terms, contact support@intellocarbon.com."],
  },
];

export default function TermsPage() {
  return (
    <div className="relative min-h-screen overflow-hidden bg-background lg:pr-[240px]">
      <div className="pointer-events-none absolute inset-0 bg-grid opacity-40" />
      <div className="pointer-events-none absolute inset-x-0 top-0 h-[520px] bg-gradient-radial-glow" />

      <MarketingHeader />

      {/* Hero */}
      <section className="relative z-10 mx-auto max-w-4xl px-6 pb-16 pt-10 text-center">
        <h1 className="text-[36px] font-semibold leading-tight text-[#E8F0F7] text-balance sm:text-[48px]">
          Terms of Service
        </h1>
        <p className="mx-auto mt-4 max-w-2xl text-balance text-[#8AA0B4] sm:text-lg">
          Intellocarbon Solutions Private Limited
        </p>
        <p className="mt-2 text-sm text-[#8AA0B4]">Effective Date: 10 July 2026</p>
      </section>

      <main className="relative z-10 mx-auto max-w-3xl px-6 pb-24">
        <p className="text-[#8AA0B4]">
          These Terms of Service (&quot;Terms&quot;) govern access to and use of the Intellocarbon platform,
          available at intellocarbon.com and any related applications, dashboards, tools, or reports
          (collectively, the &quot;Platform&quot;), operated by Intellocarbon Solutions Private Limited, a
          company incorporated under the Companies Act, 2013, having CIN U62020CT2026PTC020653 and its
          registered office at Ambikapur, Surguja, Chhattisgarh, India (&quot;Intellocarbon&quot;,
          &quot;we&quot;, &quot;us&quot;, &quot;our&quot;). By creating an account, accessing, or using the
          Platform, you (&quot;Customer&quot;, &quot;you&quot;, &quot;your&quot;) agree to be bound by these
          Terms.
        </p>

        {SECTIONS.map((section) => (
          <section key={section.heading} className="border-t border-surface-border py-10 sm:py-12">
            <h2 className="text-2xl font-semibold text-teal-500">{section.heading}</h2>
            <div className="mt-4 space-y-4 text-[#8AA0B4]">
              {section.paragraphs.map((paragraph, index) => (
                <p key={index}>{paragraph}</p>
              ))}
            </div>
          </section>
        ))}
      </main>

      <div className="relative z-10">
        <ToolFooter />
      </div>
    </div>
  );
}
