import { describe, it, expect, afterAll } from "vitest";
import fs from "fs";
import path from "path";
import { extractText, shutdownOcr } from "../textExtraction";
import { parseBillFields } from "../fieldParser";

/**
 * End-to-end through the real engines: a genuine PDF binary read by pdfjs, and
 * a genuine raster image recognised by Tesseract. The parser tests next door
 * work from text and can therefore be exhaustive; these exist to prove the two
 * engines are actually wired up, produce line-structured text, and degrade the
 * way the callers assume they do.
 *
 * Fixtures are generated by scripts/generate-bill-fixtures.js.
 */

const fixture = (name: string) => path.join(__dirname, "fixtures", name);
const read = (name: string) => fs.readFileSync(fixture(name));

afterAll(async () => {
  // Tesseract holds a worker process open; without this the run never exits.
  await shutdownOcr();
});

describe("PDF text layer", () => {
  it("reads a real PDF and parses every field out of it", async () => {
    const result = await extractText(read("msedcl-ht-industrial.pdf"));
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.engine).toBe("PDF_TEXT_LAYER");
    // No recognition step happened, so there is no recognition confidence to
    // report — and reporting one would imply a doubt that doesn't exist.
    expect(result.ocrMeanConfidence).toBeNull();

    const parsed = parseBillFields(result.text);
    expect(parsed.discomCode).toBe("MSEDCL");
    expect(parsed.state).toBe("Maharashtra");
    expect(parsed.unitsConsumedKwh).toBe(1_250_000);
    expect(parsed.sanctionedLoadValue).toBe(2500);
    expect(parsed.ratePerUnitInr).toBe(8.45);
    expect(parsed.billingPeriodStart?.toISOString().slice(0, 10)).toBe("2026-06-01");
  });

  it("preserves line breaks, which the parser's same-line rule depends on", async () => {
    const result = await extractText(read("msedcl-ht-industrial.pdf"));
    if (!result.ok) throw new Error("extraction failed");
    expect(result.text.split("\n").length).toBeGreaterThan(5);
  });

  it("round-trips the other discom layouts through a real PDF", async () => {
    const cases: Array<[string, string, number | null]> = [
      ["tangedco-ht.pdf", "TANGEDCO", 845_320],
      ["bescom-lt.pdf", "BESCOM", 42_500],
      ["pvvnl-billing-month.pdf", "PVVNL", 96_400],
      // kVAh only — the PDF reads fine, the units field is deliberately null.
      ["torrent-kvah-only.pdf", "TORRENT_POWER", null],
    ];
    for (const [file, discomCode, kwh] of cases) {
      const result = await extractText(read(file));
      expect(result.ok, file).toBe(true);
      if (!result.ok) continue;
      const parsed = parseBillFields(result.text);
      expect(parsed.discomCode, file).toBe(discomCode);
      expect(parsed.unitsConsumedKwh, file).toBe(kwh);
    }
  });

  it("extracts nothing usable from a PDF that is not a bill", async () => {
    const result = await extractText(read("not-a-bill.pdf"));
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const parsed = parseBillFields(result.text);
    expect(parsed.unitsConsumedKwh).toBeNull();
    expect(parsed.discomCode).toBeNull();
  });
});

describe("graceful failure", () => {
  it("reports an unsupported file type rather than throwing", async () => {
    const result = await extractText(Buffer.from("just some plain text, not a document"));
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.reason).toBe("UNSUPPORTED_FILE_TYPE");
  });

  it("reports a corrupt PDF rather than throwing", async () => {
    const result = await extractText(Buffer.from("%PDF-1.4\nnot actually a pdf body"));
    expect(result.ok).toBe(false);
    if (!result.ok) expect(["CORRUPT_FILE", "NO_TEXT_LAYER"]).toContain(result.reason);
  });

  it("reports a PDF with no text layer instead of returning empty fields", async () => {
    // A structurally valid PDF whose only page carries no text at all.
    const blank = Buffer.from(
      "%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n" +
        "3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj\ntrailer<</Root 1 0 R>>",
      "latin1",
    );
    const result = await extractText(blank);
    expect(result.ok).toBe(false);
    if (!result.ok) expect(["NO_TEXT_LAYER", "CORRUPT_FILE"]).toContain(result.reason);
  });
});

describe("OCR", () => {
  // Tesseract loads a language model on first use; a cold cache downloads it.
  it(
    "recognises a rasterised bill and reports a page confidence",
    async () => {
      const png = fixture("msedcl-ht-industrial.png");
      if (!fs.existsSync(png)) {
        throw new Error("Missing OCR fixture — run: node scripts/generate-bill-fixtures.js");
      }
      const result = await extractText(fs.readFileSync(png));
      expect(result.ok).toBe(true);
      if (!result.ok) return;

      expect(result.engine).toBe("OCR_IMAGE");
      expect(typeof result.ocrMeanConfidence).toBe("number");

      const parsed = parseBillFields(result.text, { ocrMeanConfidence: result.ocrMeanConfidence });
      // The consumption figure is the one that matters — it is the only field
      // that pre-fills a Scope 2 input.
      expect(parsed.unitsConsumedKwh).toBe(1_250_000);
      expect(parsed.discomCode).toBe("MSEDCL");
      expect(parsed.billingPeriodStart?.toISOString().slice(0, 10)).toBe("2026-06-01");
      expect(parsed.ratePerUnitInr).toBe(8.45);
    },
    120_000,
  );

  it(
    "drops a field whose unit OCR misread, rather than reporting a wrong unit",
    async () => {
      // Tesseract reads "2500 KVA" on this page as "2500 EVA". The number
      // survived, the unit did not — and a sanctioned load whose unit is
      // unknown is not a sanctioned load, because KVA, KW and HP are not
      // interchangeable. The correct outcome is a null and a prompt to type
      // it in, which is what this asserts.
      const result = await extractText(fs.readFileSync(fixture("msedcl-ht-industrial.png")));
      if (!result.ok) throw new Error("extraction failed");
      const parsed = parseBillFields(result.text, { ocrMeanConfidence: result.ocrMeanConfidence });
      expect(parsed.sanctionedLoadValue).toBeNull();
      expect(parsed.fieldMeta.sanctionedLoad.status).toBe("NOT_EXTRACTED");
    },
    120_000,
  );
});
